version: '2'
checks:
  similar-code:
    enabled: false
  method-lines:
    config:
      threshold: 70
plugins:
  csslint:
    enabled: true
  editorconfig:
    enabled: true
  fixme:
    enabled: true
  markdownlint:
    enabled: true
  scss-lint:
    enabled: true
  tslint:
    enabled: true
