language: node_js
sudo: false

before_script:
  - npm install

script:
  - npm run build
  - echo 'nexiumcore.com' > ./out/CNAME

deploy:
  provider: pages
  github-token: $GITHUB_TOKEN
  local-dir: ./dist
  keep-history: false
  skip-cleanup: true
  on:
    branch: master
