language: node_js
sudo: false

cache: npm

node_js:
  - 'node'

before_script:
  - npm install

script:
  - npm test
  - npm run build
  - echo 'nexiumcore.com' > ./dist/CNAME

deploy:
  provider: pages
  github-token: $GITHUB_TOKEN
  local-dir: ./dist
  keep-history: false
  skip-cleanup: true
  on:
    branch: master
